# These are supported funding model platforms

github: simowNgithub
custom: [![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://www.paypal.com/donate/?hosted_button_id=TN7A87DFKBZ88)
