- id: '1662671430272'
  alias: Automatische Übertragung der PV Werte an IDM WP
  description: Automatische Übertragung der Photovoltaik Werte an die IDM Wärmepumpe.
  trigger:
  - minutes: /3
    platform: time_pattern
  condition:
  - '{{ not is_state(''sensor.wp_aktueller_pv_uberschuss'',''sensor.idm_aktuellerphotovoltaikueberschuss'')
    }}'
  action:
  - service: script.idm_update_pv_values
    data: {}
  mode: single
